ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC:: @ 8190384
    .string "Please feel free to use that PC in\n"
    .string "the corner.\p"
    .string "The receptionist told me so.\n"
    .string "It's so kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown:: @ 81903E5
    .string "There's a POKéMON CENTER in every\n"
    .string "town ahead.\p"
    .string "They charge no money, so don't\n"
    .string "be shy about healing POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons:: @ 8190450
    .string "POKéMON CENTERS heal your tired,\n"
    .string "hurt, or fainted POKéMON.\p"
    .string "They make all POKéMON completely\n"
    .string "healthy.$"

ViridianCity_PokemonCenter_1F_Text_ReTeachMonMove:: @ 81A2B88
    .string "I'll help your POKéMON remember\n"
    .string "old moves free of charge.$"

ViridianCity_PokemonCenter_1F_Text_TeachMonMoveForScale:: @ 81A2B88
    .string "I'll teach a move to one POKéMON\n"
    .string "in exchange for a HEART SCALE.$"

ViridianCity_PokemonCenter_1F_Text_WantMeToTeachMove:: @ 81A2C63
    .string "Will you pay my price?$"

ViridianCity_PokemonCenter_1F_Text_TutorWhichMon:: @ 81A2CC3
    .string "Which POKéMON needs tutoring?$"

ViridianCity_PokemonCenter_1F_Text_TeachWhichMove:: @ 81A2CE1
    .string "Which move should I teach?$"

ViridianCity_PokemonCenter_1F_Text_NoMoveICanTeachThatMon:: @ 81A2CFC
    .string "Sorry…\p"
    .string "It doesn't appear as if I have a\n"
    .string "move I can teach that POKéMON.$"

ViridianCity_PokemonCenter_1F_Text_HandedOverScale:: @ 81A2DB3
    .string "{PLAYER} handed over one\n"
    .string "HEART SCALE in exchange.$"

ViridianCity_PokemonCenter_1F_Text_NotEnoughScales:: @ 81A2DE0
    .string "You don't have enough HEART\n"
    .string "SCALES to pay for that.$"

ViridianCity_PokemonCenter_1F_Text_CantTeachAnEgg:: @ 81A2E20
    .string "Hunh? There isn't a single move\n"
    .string "that I can teach an EGG.$"

ViridianCity_PokemonCenter_1F_EventScript_HowMayIHelp::
    .string "How may I help you?$"

ViridianCity_PokemonCenter_1F_Text_ComeAgain:: @ 81A2DE0
    .string "Come again sometime!$"
