Route2_Text_RouteSign:: @ 818345E
    .string "ROUTE 2\n"
    .string "VIRIDIAN CITY - PEWTER CITY$"

Route2_Text_DiglettsCave:: @ 8183482
    .string "DIGLETT'S CAVE$"

Route2_Text_SeeYouAtTheGym::
    .string "Hi I'm BROCK!\n"
    .string "I'm PEWTER CITY's gym leader.\p"
    .string "I like to explore the caves to\n"
    .string "look for more ROCK type POKEMON.\p"
    .string "But this one only had DIGLETTs.\n"
    .string "What a waste!\p"
    .string "If you want to challenge me,\n"
    .string "meet me at the PEWTER CITY gym.$"
